BOT_TOKEN = "PUT_YOUR_BOT_TOKEN_HERE"

DEFAULT_TIMEFRAME = "4h"
SCAN_INTERVAL = 120  # seconds

HALAL_COINS = [
    "BTCUSDT", "ETHUSDT", "BNBUSDT",
    "ADAUSDT", "XRPUSDT", "SOLUSDT"
]

ALL_COINS = HALAL_COINS + [
    "DOGEUSDT", "AVAXUSDT", "MATICUSDT"
]
