import os

BOT_TOKEN = os.getenv("BOT_TOKEN")

HALAL_COINS = ["BTCUSDT", "ETHUSDT", "BNBUSDT"]
ALL_COINS = ["BTCUSDT", "ETHUSDT", "BNBUSDT", "XRPUSDT", "DOGEUSDT"]

DEFAULT_TIMEFRAME = "4h"
SCAN_INTERVAL = 60
